---
- name: creates the cloud infra
  hosts: defaults
  become: true
  tasks:
    - name: Install Python and pip
      yum:
        name: ['python3', 'python3-pip', 'yum-utils']
        state: present

    - name: Install Git
      yum:
        name: git
        state: present

    - name: install Docker
      yum:
        name: docker
        update_cache: yes

    - name: Start Docker 
      service:
        name: docker
        state: restarted
        enabled: yes
      become: yes

    - name: Clone app repo
      git:
        repo: https://github.com/meitavEini/simple-python-project.git
        dest: /home/ec2-user/meitav
